name: Peregrine CI

on:
  push:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta', 'dev' or 'master'
      - name: Check Flutter Version
        run: flutter --version
      - name: Clone prêt-à-porter
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.ACTION_KEY }}"
          cd .. && git clone git@github.com:ThatNerdSquared/pret_a_porter.git
      - name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Code analysis
        run: flutter analyze
    # currently disabled because tests aren't up rn
    # - name: Run tests
    #   run: flutter test
